# Generated by Django 3.2.21 on 2024-01-14 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=200, verbose_name='Job Title')),
                ('job_description', models.TextField(max_length=2000, verbose_name='Job Description')),
                ('job_photo1', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Job Photo 1')),
                ('job_photo2', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Job Photo 2')),
                ('job_photo3', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Job Photo 3')),
            ],
        ),
    ]
