# Generated by Django 3.2.21 on 2024-01-14 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20240114_1412'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product_image',
            new_name='JobImage',
        ),
    ]
