# Generated by Django 3.2.21 on 2024-01-14 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_rename_product_image_jobimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobimage',
            old_name='job_image',
            new_name='job',
        ),
    ]
