# Generated by Django 3.2.21 on 2024-01-14 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_rename_job_image_jobimage_job'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobimage',
            options={},
        ),
        migrations.RemoveField(
            model_name='jobimage',
            name='time_created',
        ),
    ]
